/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Intellecta
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var Intellecta = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("brain-circuit", "Card Generator", () => {
      console.log("Will be updated!");
    });
  }
  async onunload() {
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHtQbHVnaW59IGZyb20gXCJvYnNpZGlhblwiO1xyXG5cclxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgSW50ZWxsZWN0YSBleHRlbmRzIFBsdWdpbiB7XHJcbiAgICBhc3luYyBvbmxvYWQoKSB7XHJcbiAgICAgICAgLy8gQ29uZmlndXJlIHJlc291cmNlcyBuZWVkZWQgYnkgdGhlIHBsdWdpblxyXG4gICAgICAgIC8vIFRoaXMgcnVucyB3aGVuIHRoZSBwbHVnaW4gaXMgc3RhcnRlZFxyXG5cclxuICAgICAgICAvLyBBZGQgcmliYm9uIGFjdGlvblxyXG4gICAgICAgIHRoaXMuYWRkUmliYm9uSWNvbihcImJyYWluLWNpcmN1aXRcIixcIkNhcmQgR2VuZXJhdG9yXCIsKCkgPT4ge1xyXG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcIldpbGwgYmUgdXBkYXRlZCFcIilcclxuICAgICAgICAgICAgLy9IYXMgdG8gY3JlYXRlIHRocmVlIG9wdGlvbnMgKGxpdGVyYXR1cmUsIHBlcm1lbmFudCwgY29ubmVjdGlvbilcclxuICAgICAgICB9KVxyXG4gICAgfVxyXG4gICAgYXN5bmMgb251bmxvYWQoKSB7XHJcbiAgICAgICAgLy8gUmVsZWFzZSBhbnkgcmVzb3VyY2VzIGNvbmZpZ3VyZWQgYnkgdGhlIHBsdWdpblxyXG4gICAgICAgIC8vIFRoaXMgcnVucyB3aGVuIHRoZSBwbHVnaW4gaXMgZGlzYWJsZWRcclxuICAgIH1cclxufSJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQSxzQkFBcUI7QUFFckIsSUFBcUIsYUFBckIsY0FBd0MsdUJBQU87QUFBQSxFQUMzQyxNQUFNLFNBQVM7QUFLWCxTQUFLLGNBQWMsaUJBQWdCLGtCQUFpQixNQUFNO0FBQ3RELGNBQVEsSUFBSSxrQkFBa0I7QUFBQSxJQUVsQyxDQUFDO0FBQUEsRUFDTDtBQUFBLEVBQ0EsTUFBTSxXQUFXO0FBQUEsRUFHakI7QUFDSjsiLAogICJuYW1lcyI6IFtdCn0K
